package com.myiot.myserver.data.po.system;

import java.io.Serializable;

public class Department implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myiot_department.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myiot_department.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myiot_department.code
     *
     * @mbg.generated
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myiot_department.parent_id
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myiot_department.leaf
     *
     * @mbg.generated
     */
    private Integer leaf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myiot_department.leader_id
     *
     * @mbg.generated
     */
    private String leaderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myiot_department.status
     *
     * @mbg.generated
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column myiot_department.role_id
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table myiot_department
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myiot_department.id
     *
     * @return the value of myiot_department.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myiot_department.id
     *
     * @param id the value for myiot_department.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myiot_department.name
     *
     * @return the value of myiot_department.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myiot_department.name
     *
     * @param name the value for myiot_department.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myiot_department.code
     *
     * @return the value of myiot_department.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myiot_department.code
     *
     * @param code the value for myiot_department.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myiot_department.parent_id
     *
     * @return the value of myiot_department.parent_id
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myiot_department.parent_id
     *
     * @param parentId the value for myiot_department.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myiot_department.leaf
     *
     * @return the value of myiot_department.leaf
     *
     * @mbg.generated
     */
    public Integer getLeaf() {
        return leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myiot_department.leaf
     *
     * @param leaf the value for myiot_department.leaf
     *
     * @mbg.generated
     */
    public void setLeaf(Integer leaf) {
        this.leaf = leaf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myiot_department.leader_id
     *
     * @return the value of myiot_department.leader_id
     *
     * @mbg.generated
     */
    public String getLeaderId() {
        return leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myiot_department.leader_id
     *
     * @param leaderId the value for myiot_department.leader_id
     *
     * @mbg.generated
     */
    public void setLeaderId(String leaderId) {
        this.leaderId = leaderId == null ? null : leaderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myiot_department.status
     *
     * @return the value of myiot_department.status
     *
     * @mbg.generated
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myiot_department.status
     *
     * @param status the value for myiot_department.status
     *
     * @mbg.generated
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column myiot_department.role_id
     *
     * @return the value of myiot_department.role_id
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column myiot_department.role_id
     *
     * @param roleId the value for myiot_department.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_department
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", code=").append(code);
        sb.append(", parentId=").append(parentId);
        sb.append(", leaf=").append(leaf);
        sb.append(", leaderId=").append(leaderId);
        sb.append(", status=").append(status);
        sb.append(", roleId=").append(roleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
