package com.myiot.myserver.mapper.system;

import com.myiot.myserver.data.po.system.Account;
import com.myiot.myserver.data.vo.system.UserInfo;

import java.util.List;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_account
     *
     * @mbg.generated
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_account
     *
     * @mbg.generated
     */
    Account selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_account
     *
     * @mbg.generated
     */
    List<Account> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Account record);

    /**
     * 账户名是否存在
     * @param accountName
     * @return
     */
    int countByName(String accountName);

    /**
     * 根据名称查找账户
     * @param accountName
     * @return
     */
    Account findByName(String accountName);

    /**
     * 查询用户信息
     * @param userId
     * @return
     */
    UserInfo findUserInfo(String userId);

    /**
     * 更新登录状态
     * @param account
     */
    void updateLoginStatus(Account account);

    /**
     * 更新密码
     * @param account
     * @return
     */
    int updatePassword(Account account);

    /**
     * 删除用户
     * @param userIds
     */
    void deleteAccounts(List<String> userIds);
}
