package com.myiot.myserver.mapper.system;

import com.myiot.myserver.data.po.system.Menu;
import com.myiot.myserver.data.vo.system.MenuInfo;

import java.util.List;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_menu
     *
     * @mbg.generated
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_menu
     *
     * @mbg.generated
     */
    Menu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_menu
     *
     * @mbg.generated
     */
    List<Menu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Menu record);

    /**
     * 菜单名称查重
     * @param parentId
     * @param name
     * @return
     */
    int countByName(Long parentId, String name);

    /**
     * 删除菜单
     * @param menuIds
     */
    void deleteMenus(List<Long> menuIds);

    /**
     * 查询所有菜单
     * @return
     */
    List<MenuInfo> queryAll();

    /**
     * 查询菜单
     * @param menuId
     * @return
     */
    MenuInfo queryById(Long menuId);
}
