package com.myiot.myserver.mapper.system;

import com.myiot.myserver.data.po.system.Menu;
import com.myiot.myserver.data.po.system.Role;
import com.myiot.myserver.data.vo.BaseQuery;
import com.myiot.myserver.data.vo.system.RoleInfo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_role
     *
     * @mbg.generated
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_role
     *
     * @mbg.generated
     */
    Role selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_role
     *
     * @mbg.generated
     */
    List<Role> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Role record);

    /**
     * 根据角色名称查询
     * @param roleName
     * @return
     */
    int countByName(@Param("roleName") String roleName);

    /**
     * 分页查询角色
     * @return
     */
    List<RoleInfo> queryRoles(BaseQuery query);

    /**
     * 删除角色
     * @param roleIds
     */
    void deleteRoles(List<String> roleIds);
}
