package com.myiot.myserver.mapper.system;

import com.myiot.myserver.data.po.system.Menu;
import com.myiot.myserver.data.po.system.RoleMenu;
import com.myiot.myserver.data.vo.system.MenuDetailInfo;

import java.util.List;

public interface RoleMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_role_menu
     *
     * @mbg.generated
     */
    int insert(RoleMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_role_menu
     *
     * @mbg.generated
     */
    List<RoleMenu> selectAll();

    /**
     * 批量添加角色菜单
     * @param roleMenuList
     * @return
     */
    int insertBatch(List<RoleMenu> roleMenuList);

    /**
     * 查询角色的菜单权限
     * @param roleId
     * @return
     */
    List<Menu> queryRoleMenus(String roleId);

    /**
     * 删除角色对应的菜单
     * @param roleId
     */
    void removeByRoleId(String roleId);

    /**
     * 删除角色对应的菜单
     * @param roleIds
     */
    void deleteRoleMenus(List<String> roleIds);
}
