package com.myiot.myserver.mapper.system;

import com.myiot.myserver.data.po.system.User;
import com.myiot.myserver.data.vo.system.UserInfo;
import com.myiot.myserver.data.vo.system.UserQuery;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

    List<UserInfo> queryByPage(UserQuery query);

    /**
     * 删除用户信息
     * @param userIds
     */
    void deleteUsers(List<String> userIds);
}
