package com.myiot.myserver.mapper.system;

import com.myiot.myserver.data.po.system.UserToken;
import java.util.List;

public interface UserTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_user_token
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_user_token
     *
     * @mbg.generated
     */
    int insert(UserToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_user_token
     *
     * @mbg.generated
     */
    UserToken selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_user_token
     *
     * @mbg.generated
     */
    List<UserToken> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table myiot_user_token
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserToken record);

    /**
     * 查询用户Token
     * @param userId
     * @return
     */
    UserToken queryByUserId(String userId);

    /**
     * 根据token查询数据
     * @param token
     * @return
     */
    UserToken selectByToken(String token);

    /**
     * 删除用户Token
     * @param userIds
     */
    void deleteTokens(List<String> userIds);
}
